# Generated by Django 3.1.4 on 2020-12-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restmap', '0002_remove_yelpuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yelpuser',
            name='user_id',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
